// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAqB29BYf5khnHDMab9M3DF6x3fFxl5Mg',
    appId: '1:48053701546:web:8168d586aa3c37f02239d3',
    messagingSenderId: '48053701546',
    projectId: 'note-app-dcff6',
    authDomain: 'note-app-dcff6.firebaseapp.com',
    storageBucket: 'note-app-dcff6.appspot.com',
    measurementId: 'G-C2DVWPW2GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU36LSWTKPAveVP4HmxDYoqH7FRAqhGUc',
    appId: '1:48053701546:android:ec906f6d3f776b802239d3',
    messagingSenderId: '48053701546',
    projectId: 'note-app-dcff6',
    storageBucket: 'note-app-dcff6.appspot.com',
  );
}
